lamorel_args:
  log_level: info
  gloo_timeout: 1800
  allow_subgraph_use_whith_gradient: false
  distributed_setup_args:
    n_rl_processes: 1
    n_llm_processes: 1
  accelerate_args:
    config_file: ../configs/accelerate/default_config.yaml
    machine_rank: 0
    num_machines: 2
  llm_args:
    model_type: causal
    dtype: float16
    model_path: /beegfs/abouyghf/Mistral_7B
    pretrained: true
    minibatch_size: 8
    pre_encode_inputs: false
    load_in_4bit: false
    parallelism:
      use_gpu: true
      model_parallelism_size: 1
      synchronize_gpus_after_scoring: false
      empty_cuda_cache_after_scoring: false
rl_script_args:
  path: ???
